server:
  port: 8088
spring:
  application:
    name: gateway-zuulserver
eureka:
    client:
      serviceUrl:
        defaultZone: http://${eureka.host:192.168.0.101}:${eureka.port:8761}/eureka/
    instance:
      prefer-ip-address: true
    management:
      endpoints:
    web:
      exposure:
        include: hystrix.stream
feign:
  hystrix:
    enabled: true
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000
  MaxAutoRetries: 0 #对第一次请求的服务的重试次数
  MaxAutoRetriesNextServer: 0 #要重试的下一个服务的最大数量（不包括第一个服务）
  OkToRetryOnAllOperations: false
hystrix:
  threadpool:
    default:
      coreSize: 20
      maximumSize: 50
      maxQueueSize: -1
      allowMaximumSizeToDivergeFromCoreSize: true
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            interruptOnTimeout: false
            timeoutInMilliseconds: 15000
zuul:
  routes:
    api:
      path: /user/**
      service-id: learn-recelver
    order:
      path: /order/**
      service-id: learn-order
  host:
    max-total-connections: 500000
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000