server:
  port: 8088
  servlet:
    context-path: /
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 140.143.161.107:8848
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://140.143.161.107:6311/ureport?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: zhaofapwd
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      min-evictable-idle-time-millis: 30000
      filters: stat
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*
        session-stat-enable: false
        session-stat-max-count: 1000
        principal-session-name: admin
        principal-cookie-name: admin
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-password: admin
        login-username: admin
  application:
    name: Ureport2