spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      #      username: admin
      #      password: admin
      database: learn
  application:
    name: learn-send
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        tags: version=1.0,author=zhaofa
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        prefer-ip-address: false
        enabled: true
      enabled: true
    inetutils:
      use-only-site-local-interfaces: true

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/learn?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
#mybatis-plus
server:
  port: 8081
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.wwjswly.learn.entity
logging:
  level:
    com.wwjswly.learn: debug
  file: send.log
  path: ../../
debug: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always