spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      #      username: admin
      #      password: admin
      database: learn
  application:
    name: learn-send
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/learn?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
#mybatis-plus
server:
  port: 8081
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.wwjswly.learn.entity
logging:
  level:
    root: debug
debug: true