spring:
  data:
    mongodb:
      host: 140.143.161.107
      port: 27017
#      username: admin
#      password: admin
      database: learn
  application:
    name: learn-goods
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://192.168.0.101:8761/eureka/
#  instance:
#    prefer-ip-address: true
  rabbitmq:
    host: 140.143.161.107
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    connection-timeout: 15000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://140.143.161.107:3306/qingyun_goods?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
#mybatis-plus
server:
  port: 8082
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.wwjswly.learn.entity.goods
logging:
  level:
    com.wwjswly.learn: debug
#  file: send.log
#  path: ../../
debug: true
eureka:
  client:
    serviceUrl:
#      defaultZone: http://${eureka.host:192.168.0.101}:${eureka.port:8761}/eureka/
      defaultZone: http://140.143.161.107:8761/eureka/
  instance:
    prefer-ip-address: true
  management:
    endpoints:
  web:
    exposure:
      include: hystrix.stream