spring:
  data:
    mongodb:
      host: 140.143.161.107
      port: 27017
#      username: admin
#      password: admin
      database: learn
  application:
    name: learn-order
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
  rabbitmq:
    host: 140.143.161.107
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    connection-timeout: 15000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://140.143.161.107:3306/learn?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
#mybatis-plus
server:
  port: 8081
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.wwjswly.learn.entity
logging:
  level:
    com.wwjswly.learn: debug
#  file: send.log
#  path: ../../
debug: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always