spring:
  redis:
    database: 0
    password: zhaofapwd
    host: 140.143.161.107
    port: 6379
    lettuce:
      pool:
        max-active:  100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 10000
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  #      defaultZone: http://${eureka.host:192.168.0.101}:${eureka.port:8761}/eureka/

  instance:
    prefer-ip-address: true
  management:
    endpoints:
  web:
    exposure:
      include: hystrix.stream
logging:
  level:
    com.wwjswly.learnwebflux: debug

