spring:
  data:
    mongodb:
      host: 140.143.161.107
      port: 27017
      database: learn
  #      username: admin
  #      password: admin
  application:
    name: learn-recelver
  rabbitmq:
    host: 140.143.161.107
    port: 5672
    username: admin
    password: admin
    virtual-host: /
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://140.143.161.107:3306/learn?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.101:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8011
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.wwjswly.learn.entity
logging:
  level:
    com.wwjswly.learn: debug
debug: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
hystrix:
  metrics:
    enabled: true
    polling-interval-ms: 20000